/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./types/db";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAccountsRowSchemaSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicAccountsInsertSchemaSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicAccountsUpdateSchemaSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});
