import { Category, Venture, Industry } from "./types";

export const categories: Category[] = [
  {
    label: "Featured",
    href: "/explore?list=featured",
    description: "Our most promising and notable investment opportunities",
  },
  {
    label: "Latest",
    href: "/explore?list=latest",
    description: "Recently added ventures seeking investment",
  },
  {
    label: "Aquired",
    href: "/explore?list=aquired",
    description: "Success stories of ventures that have been acquired",
  },
  {
    label: "Upcoming",
    href: "/explore?list=upcoming",
    description: "Preview ventures that will be available for investment soon",
  },
  {
    label: "Real Estate",
    href: "/explore?list=real-estate",
    description: "Property and real estate investment opportunities",
  },
];

export const industries: Industry[] = [
  "Artificial Intelligence",
  "Technology",
  "Enterprise Software",
  "Real Estate",
  "Construction",
  "Sustainability",
  "Healthcare",
  "Biotechnology",
  "Transportation",
  "Agriculture",
  "Urban Planning",
  "Property Management",
  "Entertainment",
  "Virtual Reality",
  "Energy",
  "Research",
  "Finance",
  "Cryptocurrency",
  "Education",
  "Food & Beverage",
  "Logistics",
  "Manufacturing",
  "Retail",
  "Travel & Tourism",
  "IoT",
  "Insurance",
  "Legal",
  "Media & Entertainment",
  "Non-Profit",
  "Others",
];

export const ventures: Venture[] = [
  {
    title: "TechFlow AI",
    slug: "techflow-ai",
    description: "AI-powered workflow automation platform for enterprises",
    logoUrl: "/logos/techflow.png",
    category: "Featured",
    location: "San Francisco, CA",
    industries: [
      "Technology",
      "Artificial Intelligence",
      "Enterprise Software",
    ],
  },
  {
    title: "GreenBuild Construction",
    slug: "greenbuild-construction",
    description: "Sustainable construction and real estate development",
    logoUrl: "/logos/greenbuild.png",
    category: "Featured",
    location: "Portland, OR",
    industries: ["Real Estate", "Construction", "Sustainability"],
  },
  {
    title: "HealthTech Solutions",
    slug: "healthtech-solutions",
    description: "Digital health platform for remote patient monitoring",
    logoUrl: "/logos/healthtech.png",
    category: "Featured",
    location: "Boston, MA",
    industries: ["Healthcare", "Technology", "Biotechnology"],
  },
  {
    title: "InsurTech Pro",
    slug: "insurtech-pro",
    description: "AI-driven insurance underwriting and claims processing",
    logoUrl: "/logos/insurtech.png",
    category: "Featured",
    location: "Hartford, CT",
    industries: ["Insurance", "Technology", "Artificial Intelligence"],
  },
  {
    title: "LegalTech AI",
    slug: "legaltech-ai",
    description: "AI-powered legal document analysis and contract management",
    logoUrl: "/logos/legaltech.png",
    category: "Featured",
    location: "Washington, DC",
    industries: ["Legal", "Technology", "Artificial Intelligence"],
  },
  {
    title: "MediaStream",
    slug: "mediastream",
    description: "Next-generation content streaming and distribution platform",
    logoUrl: "/logos/mediastream.png",
    category: "Featured",
    location: "Los Angeles, CA",
    industries: ["Media & Entertainment", "Technology", "Entertainment"],
  },
  {
    title: "CryptoTrade Pro",
    slug: "cryptotrade-pro",
    description: "Advanced cryptocurrency trading platform",
    logoUrl: "/logos/cryptotrade.png",
    category: "Latest",
    location: "Miami, FL",
    industries: ["Finance", "Cryptocurrency", "Technology"],
  },
  {
    title: "EduLearn Platform",
    slug: "edulearn-platform",
    description: "AI-powered personalized learning platform",
    logoUrl: "/logos/edulearn.png",
    category: "Latest",
    location: "Austin, TX",
    industries: ["Education", "Technology", "Artificial Intelligence"],
  },
  {
    title: "FoodTech Delivery",
    slug: "foodtech-delivery",
    description: "Automated food delivery and kitchen management system",
    logoUrl: "/logos/foodtech.png",
    category: "Latest",
    location: "Chicago, IL",
    industries: ["Food & Beverage", "Technology", "Logistics"],
  },
  {
    title: "RetailTech Solutions",
    slug: "retailtech-solutions",
    description: "Smart retail analytics and inventory management platform",
    logoUrl: "/logos/retailtech.png",
    category: "Latest",
    location: "Atlanta, GA",
    industries: ["Retail", "Technology", "IoT"],
  },
  {
    title: "TravelSmart",
    slug: "travelsmart",
    description: "AI-powered travel planning and booking platform",
    logoUrl: "/logos/travelsmart.png",
    category: "Latest",
    location: "Las Vegas, NV",
    industries: ["Travel & Tourism", "Technology", "Artificial Intelligence"],
  },
  {
    title: "ManufactureTech",
    slug: "manufacturetech",
    description: "Smart manufacturing and industrial automation solutions",
    logoUrl: "/logos/manufacturetech.png",
    category: "Latest",
    location: "Detroit, MI",
    industries: ["Manufacturing", "Technology", "IoT"],
  },
  {
    title: "SmartHome Systems",
    slug: "smarthome-systems",
    description: "IoT solutions for home automation",
    logoUrl: "/logos/smarthome.png",
    category: "Aquired",
    location: "Seattle, WA",
    industries: ["Technology", "IoT", "Real Estate"],
  },
  {
    title: "BioGen Research",
    slug: "biogen-research",
    description: "Innovative biotechnology research and development",
    logoUrl: "/logos/biogen.png",
    category: "Aquired",
    location: "Cambridge, MA",
    industries: ["Biotechnology", "Healthcare", "Research"],
  },
  {
    title: "EcoEnergy Solutions",
    slug: "ecoenergy-solutions",
    description: "Renewable energy technology and infrastructure",
    logoUrl: "/logos/ecoenergy.png",
    category: "Aquired",
    location: "Denver, CO",
    industries: ["Energy", "Sustainability", "Technology"],
  },
  {
    title: "NonProfitTech",
    slug: "nonprofittech",
    description: "Technology solutions for non-profit organizations",
    logoUrl: "/logos/nonprofittech.png",
    category: "Aquired",
    location: "Philadelphia, PA",
    industries: ["Non-Profit", "Technology", "Others"],
  },
  {
    title: "HealthAI Labs",
    slug: "healthai-labs",
    description: "AI-driven drug discovery platform",
    logoUrl: "/logos/healthai.png",
    category: "Aquired",
    location: "San Diego, CA",
    industries: ["Healthcare", "Artificial Intelligence", "Biotechnology"],
  },
  {
    title: "LogisticsPro",
    slug: "logisticspro",
    description: "Smart logistics and supply chain management platform",
    logoUrl: "/logos/logisticspro.png",
    category: "Aquired",
    location: "Houston, TX",
    industries: ["Logistics", "Technology", "IoT"],
  },
  {
    title: "MetaVerse Studios",
    slug: "metaverse-studios",
    description: "Virtual reality content creation platform",
    logoUrl: "/logos/metaverse.png",
    category: "Upcoming",
    location: "Los Angeles, CA",
    industries: ["Technology", "Entertainment", "Virtual Reality"],
  },
  {
    title: "UrbanMobility",
    slug: "urban-mobility",
    description: "Electric vehicle sharing and smart city solutions",
    logoUrl: "/logos/urbanmobility.png",
    category: "Upcoming",
    location: "Detroit, MI",
    industries: ["Transportation", "Technology", "Sustainability"],
  },
  {
    title: "AgroTech Farms",
    slug: "agrotech-farms",
    description: "Smart farming and agricultural technology",
    logoUrl: "/logos/agrotech.png",
    category: "Upcoming",
    location: "Sacramento, CA",
    industries: ["Agriculture", "Technology", "Sustainability"],
  },
  {
    title: "FinTech Innovations",
    slug: "fintech-innovations",
    description: "Next-generation financial technology solutions",
    logoUrl: "/logos/fintech.png",
    category: "Upcoming",
    location: "Charlotte, NC",
    industries: ["Finance", "Technology", "Cryptocurrency"],
  },
  {
    title: "EdTech Future",
    slug: "edtech-future",
    description: "Virtual reality education platform",
    logoUrl: "/logos/edtech.png",
    category: "Upcoming",
    location: "Phoenix, AZ",
    industries: ["Education", "Virtual Reality", "Technology"],
  },
  {
    title: "SpaceTech Ventures",
    slug: "spacetech-ventures",
    description: "Commercial space technology and research",
    logoUrl: "/logos/spacetech.png",
    category: "Upcoming",
    location: "Houston, TX",
    industries: ["Technology", "Research", "Others"],
  },
  {
    title: "SmartSpace Properties",
    slug: "smartspace-properties",
    description: "AI-powered real estate management platform",
    logoUrl: "/logos/smartspace.png",
    category: "Real Estate",
    location: "New York, NY",
    industries: ["Real Estate", "Technology", "Artificial Intelligence"],
  },
  {
    title: "Urban Development Co",
    slug: "urban-development-co",
    description: "Sustainable urban development and planning",
    logoUrl: "/logos/urbandev.png",
    category: "Real Estate",
    location: "Toronto, ON",
    industries: ["Real Estate", "Construction", "Urban Planning"],
  },
  {
    title: "PropTech Solutions",
    slug: "proptech-solutions",
    description: "Property technology and management solutions",
    logoUrl: "/logos/proptech.png",
    category: "Real Estate",
    location: "Vancouver, BC",
    industries: ["Real Estate", "Technology", "Property Management"],
  },
  {
    title: "SmartRental",
    slug: "smartrental",
    description: "AI-driven rental property management platform",
    logoUrl: "/logos/smartrental.png",
    category: "Real Estate",
    location: "Chicago, IL",
    industries: ["Real Estate", "Technology", "Property Management"],
  },
  {
    title: "GreenSpace Development",
    slug: "greenspace-development",
    description: "Sustainable commercial real estate development",
    logoUrl: "/logos/greenspace.png",
    category: "Real Estate",
    location: "Seattle, WA",
    industries: ["Real Estate", "Construction", "Sustainability"],
  },
  {
    title: "RealtyTech Pro",
    slug: "realtytech-pro",
    description: "Virtual reality real estate tours and marketing",
    logoUrl: "/logos/realtytech.png",
    category: "Real Estate",
    location: "Miami, FL",
    industries: ["Real Estate", "Virtual Reality", "Technology"],
  },
];
