/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./src/zod";
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicAccountsRowSchema = z.infer<
  typeof generated.publicAccountsRowSchemaSchema
>;
export type PublicAccountsInsertSchema = z.infer<
  typeof generated.publicAccountsInsertSchemaSchema
>;
export type PublicAccountsUpdateSchema = z.infer<
  typeof generated.publicAccountsUpdateSchemaSchema
>;
