/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./src/zod";
export type PublicBankAccountHolderCategories = z.infer<
  typeof generated.publicBankAccountHolderCategoriesSchema
>;
export type PublicBankAccountSubTypes = z.infer<
  typeof generated.publicBankAccountSubTypesSchema
>;
export type PublicBankAccountTypes = z.infer<
  typeof generated.publicBankAccountTypesSchema
>;
export type PublicBankAccountVerificationStatuses = z.infer<
  typeof generated.publicBankAccountVerificationStatusesSchema
>;
export type PublicTransactionCodes = z.infer<
  typeof generated.publicTransactionCodesSchema
>;
export type PublicTransactionPaymentChannels = z.infer<
  typeof generated.publicTransactionPaymentChannelsSchema
>;
export type PublicTransactionPersonalFinanceCategoryConfidenceLevels = z.infer<
  typeof generated.publicTransactionPersonalFinanceCategoryConfidenceLevelsSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicAccountsRowSchema = z.infer<
  typeof generated.publicAccountsRowSchemaSchema
>;
export type PublicAccountsInsertSchema = z.infer<
  typeof generated.publicAccountsInsertSchemaSchema
>;
export type PublicAccountsUpdateSchema = z.infer<
  typeof generated.publicAccountsUpdateSchemaSchema
>;
export type PublicLinkedAccountPlaidCredentialsRowSchema = z.infer<
  typeof generated.publicLinkedAccountPlaidCredentialsRowSchemaSchema
>;
export type PublicLinkedAccountPlaidCredentialsInsertSchema = z.infer<
  typeof generated.publicLinkedAccountPlaidCredentialsInsertSchemaSchema
>;
export type PublicLinkedAccountPlaidCredentialsUpdateSchema = z.infer<
  typeof generated.publicLinkedAccountPlaidCredentialsUpdateSchemaSchema
>;
export type PublicLinkedAccountPlaidCredentialsRelationshipsSchema = z.infer<
  typeof generated.publicLinkedAccountPlaidCredentialsRelationshipsSchemaSchema
>;
export type PublicLinkedAccountsRowSchema = z.infer<
  typeof generated.publicLinkedAccountsRowSchemaSchema
>;
export type PublicLinkedAccountsInsertSchema = z.infer<
  typeof generated.publicLinkedAccountsInsertSchemaSchema
>;
export type PublicLinkedAccountsUpdateSchema = z.infer<
  typeof generated.publicLinkedAccountsUpdateSchemaSchema
>;
export type PublicLinkedAccountsRelationshipsSchema = z.infer<
  typeof generated.publicLinkedAccountsRelationshipsSchemaSchema
>;
export type PublicPlaidBankAccountsRowSchema = z.infer<
  typeof generated.publicPlaidBankAccountsRowSchemaSchema
>;
export type PublicPlaidBankAccountsInsertSchema = z.infer<
  typeof generated.publicPlaidBankAccountsInsertSchemaSchema
>;
export type PublicPlaidBankAccountsUpdateSchema = z.infer<
  typeof generated.publicPlaidBankAccountsUpdateSchemaSchema
>;
export type PublicPlaidBankAccountsRelationshipsSchema = z.infer<
  typeof generated.publicPlaidBankAccountsRelationshipsSchemaSchema
>;
export type PublicPlaidTransactionsRowSchema = z.infer<
  typeof generated.publicPlaidTransactionsRowSchemaSchema
>;
export type PublicPlaidTransactionsInsertSchema = z.infer<
  typeof generated.publicPlaidTransactionsInsertSchemaSchema
>;
export type PublicPlaidTransactionsUpdateSchema = z.infer<
  typeof generated.publicPlaidTransactionsUpdateSchemaSchema
>;
export type PublicPlaidTransactionsRelationshipsSchema = z.infer<
  typeof generated.publicPlaidTransactionsRelationshipsSchemaSchema
>;
export type PublicQuickBooksOauthCredentialsRowSchema = z.infer<
  typeof generated.publicQuickBooksOauthCredentialsRowSchemaSchema
>;
export type PublicQuickBooksOauthCredentialsInsertSchema = z.infer<
  typeof generated.publicQuickBooksOauthCredentialsInsertSchemaSchema
>;
export type PublicQuickBooksOauthCredentialsUpdateSchema = z.infer<
  typeof generated.publicQuickBooksOauthCredentialsUpdateSchemaSchema
>;
export type PublicQuickBooksOauthCredentialsRelationshipsSchema = z.infer<
  typeof generated.publicQuickBooksOauthCredentialsRelationshipsSchemaSchema
>;
export type PublicQuickBooksOauthStatesRowSchema = z.infer<
  typeof generated.publicQuickBooksOauthStatesRowSchemaSchema
>;
export type PublicQuickBooksOauthStatesInsertSchema = z.infer<
  typeof generated.publicQuickBooksOauthStatesInsertSchemaSchema
>;
export type PublicQuickBooksOauthStatesUpdateSchema = z.infer<
  typeof generated.publicQuickBooksOauthStatesUpdateSchemaSchema
>;
export type PublicQuickBooksOauthStatesRelationshipsSchema = z.infer<
  typeof generated.publicQuickBooksOauthStatesRelationshipsSchemaSchema
>;
