/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./src/zod";
export type PublicPlaidAccountSubtype = z.infer<
  typeof generated.publicPlaidAccountSubtypeSchema
>;
export type PublicPlaidAccountType = z.infer<
  typeof generated.publicPlaidAccountTypeSchema
>;
export type PublicPlaidConfidenceLevel = z.infer<
  typeof generated.publicPlaidConfidenceLevelSchema
>;
export type PublicPlaidTransactionCode = z.infer<
  typeof generated.publicPlaidTransactionCodeSchema
>;
export type PublicPlaidTransactionPaymentChannel = z.infer<
  typeof generated.publicPlaidTransactionPaymentChannelSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicAccountsRowSchema = z.infer<
  typeof generated.publicAccountsRowSchemaSchema
>;
export type PublicAccountsInsertSchema = z.infer<
  typeof generated.publicAccountsInsertSchemaSchema
>;
export type PublicAccountsUpdateSchema = z.infer<
  typeof generated.publicAccountsUpdateSchemaSchema
>;
export type PublicCompaniesRowSchema = z.infer<
  typeof generated.publicCompaniesRowSchemaSchema
>;
export type PublicCompaniesInsertSchema = z.infer<
  typeof generated.publicCompaniesInsertSchemaSchema
>;
export type PublicCompaniesUpdateSchema = z.infer<
  typeof generated.publicCompaniesUpdateSchemaSchema
>;
export type PublicCompaniesRelationshipsSchema = z.infer<
  typeof generated.publicCompaniesRelationshipsSchemaSchema
>;
export type PublicPlaidBankAccountsRowSchema = z.infer<
  typeof generated.publicPlaidBankAccountsRowSchemaSchema
>;
export type PublicPlaidBankAccountsInsertSchema = z.infer<
  typeof generated.publicPlaidBankAccountsInsertSchemaSchema
>;
export type PublicPlaidBankAccountsUpdateSchema = z.infer<
  typeof generated.publicPlaidBankAccountsUpdateSchemaSchema
>;
export type PublicPlaidBankAccountsRelationshipsSchema = z.infer<
  typeof generated.publicPlaidBankAccountsRelationshipsSchemaSchema
>;
export type PublicPlaidCredentialsRowSchema = z.infer<
  typeof generated.publicPlaidCredentialsRowSchemaSchema
>;
export type PublicPlaidCredentialsInsertSchema = z.infer<
  typeof generated.publicPlaidCredentialsInsertSchemaSchema
>;
export type PublicPlaidCredentialsUpdateSchema = z.infer<
  typeof generated.publicPlaidCredentialsUpdateSchemaSchema
>;
export type PublicPlaidCredentialsRelationshipsSchema = z.infer<
  typeof generated.publicPlaidCredentialsRelationshipsSchemaSchema
>;
export type PublicPlaidTransactionsRowSchema = z.infer<
  typeof generated.publicPlaidTransactionsRowSchemaSchema
>;
export type PublicPlaidTransactionsInsertSchema = z.infer<
  typeof generated.publicPlaidTransactionsInsertSchemaSchema
>;
export type PublicPlaidTransactionsUpdateSchema = z.infer<
  typeof generated.publicPlaidTransactionsUpdateSchemaSchema
>;
export type PublicPlaidTransactionsRelationshipsSchema = z.infer<
  typeof generated.publicPlaidTransactionsRelationshipsSchemaSchema
>;
export type PublicQuickBooksInvoicesRowSchema = z.infer<
  typeof generated.publicQuickBooksInvoicesRowSchemaSchema
>;
export type PublicQuickBooksInvoicesInsertSchema = z.infer<
  typeof generated.publicQuickBooksInvoicesInsertSchemaSchema
>;
export type PublicQuickBooksInvoicesUpdateSchema = z.infer<
  typeof generated.publicQuickBooksInvoicesUpdateSchemaSchema
>;
export type PublicQuickBooksInvoicesRelationshipsSchema = z.infer<
  typeof generated.publicQuickBooksInvoicesRelationshipsSchemaSchema
>;
export type PublicQuickBooksOauthCredentialsRowSchema = z.infer<
  typeof generated.publicQuickBooksOauthCredentialsRowSchemaSchema
>;
export type PublicQuickBooksOauthCredentialsInsertSchema = z.infer<
  typeof generated.publicQuickBooksOauthCredentialsInsertSchemaSchema
>;
export type PublicQuickBooksOauthCredentialsUpdateSchema = z.infer<
  typeof generated.publicQuickBooksOauthCredentialsUpdateSchemaSchema
>;
export type PublicQuickBooksOauthCredentialsRelationshipsSchema = z.infer<
  typeof generated.publicQuickBooksOauthCredentialsRelationshipsSchemaSchema
>;
export type PublicQuickBooksOauthStatesRowSchema = z.infer<
  typeof generated.publicQuickBooksOauthStatesRowSchemaSchema
>;
export type PublicQuickBooksOauthStatesInsertSchema = z.infer<
  typeof generated.publicQuickBooksOauthStatesInsertSchemaSchema
>;
export type PublicQuickBooksOauthStatesUpdateSchema = z.infer<
  typeof generated.publicQuickBooksOauthStatesUpdateSchemaSchema
>;
export type PublicQuickBooksOauthStatesRelationshipsSchema = z.infer<
  typeof generated.publicQuickBooksOauthStatesRelationshipsSchemaSchema
>;
