// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-axios";
import type {
  GetAccountData,
  GetAccountError,
  GetAccountResponse,
  CreateAccountData,
  CreateAccountError,
  GetStripeIdentityData,
  GetStripeIdentityError,
  GetStripeIdentityResponse,
  GetStripeIdentityVerificationSessionUrlData,
  GetStripeIdentityVerificationSessionUrlError,
  GetStripeIdentityVerificationSessionUrlResponse,
  DeleteAccountData,
  DeleteAccountError,
  DeleteAccountResponse,
  UpdateAccountData,
  UpdateAccountError,
  UpdateAccountResponse,
  GetAccountBusinessesData,
  GetAccountBusinessesError,
  GetAccountBusinessesResponse,
  CreateBusinessImpressionData,
  CreateBusinessImpressionError,
  CreateBusinessImpressionResponse,
  DeleteBusinessFavouriteData,
  DeleteBusinessFavouriteError,
  DeleteBusinessFavouriteResponse,
  GetBusinessFavouriteStatusData,
  GetBusinessFavouriteStatusError,
  GetBusinessFavouriteStatusResponse,
  CreateBusinessFavouriteData,
  CreateBusinessFavouriteError,
  CreateBusinessFavouriteResponse,
  GetBusinessFavouriteCountData,
  GetBusinessFavouriteCountError,
  GetBusinessFavouriteCountResponse,
  GetBusinessImpressionCountData,
  GetBusinessImpressionCountError,
  GetBusinessImpressionCountResponse,
  CreateRoundFavouriteData,
  CreateRoundFavouriteError,
  CreateRoundFavouriteResponse,
  CreateRoundImpressionData,
  CreateRoundImpressionError,
  CreateRoundImpressionResponse,
  DeleteRoundFavouriteData,
  DeleteRoundFavouriteError,
  DeleteRoundFavouriteResponse,
  GetRoundFavouriteStatusData,
  GetRoundFavouriteStatusError,
  GetRoundFavouriteStatusResponse,
  GetRoundFavouriteCountData,
  GetRoundFavouriteCountError,
  GetRoundFavouriteCountResponse,
  GetRoundImpressionCountData,
  GetRoundImpressionCountError,
  GetRoundImpressionCountResponse,
  CreateBusinessData,
  CreateBusinessError,
  CreateBusinessResponse,
  GetBusinessStripeAccountData,
  GetBusinessStripeAccountError,
  GetBusinessStripeAccountResponse,
  DeleteBusinessData,
  DeleteBusinessError,
  DeleteBusinessResponse,
  GetBusinessByIdData,
  GetBusinessByIdError,
  GetBusinessByIdResponse,
  GetBusinessMembersByPageData,
  GetBusinessMembersByPageError,
  GetBusinessMembersByPageResponse,
  GetBusinessRoundCreateRequirementsData,
  GetBusinessRoundCreateRequirementsError,
  GetBusinessRoundCreateRequirementsResponse,
  GetBusinessMemberRolesData,
  GetBusinessMemberRolesError,
  GetBusinessMemberRolesResponse,
  GetBusinessRoundsByCursorData,
  GetBusinessRoundsByCursorError,
  GetBusinessRoundsByCursorResponse,
  GetBusinessRoundsByPageData,
  GetBusinessRoundsByPageError,
  GetBusinessRoundsByPageResponse,
  UpsertBusinessLegalSectionData,
  UpsertBusinessLegalSectionError,
  UpsertBusinessLegalSectionResponse,
  GetStripeDashboardUrlData,
  GetStripeDashboardUrlError,
  GetStripeDashboardUrlResponse,
  OnboardStripeConnectedAccountData,
  OnboardStripeConnectedAccountError,
  OnboardStripeConnectedAccountResponse,
  HealthCheckData,
  HealthCheckError,
  HealthCheckResponse,
  GetAllIndustriesData,
  GetAllIndustriesError,
  GetAllIndustriesResponse,
  CreateRoundInvestmentData,
  CreateRoundInvestmentError,
  CreateRoundInvestmentResponse,
  GetInvestmentByIdData,
  GetInvestmentByIdError,
  GetInvestmentByIdResponse,
  GetInvestmentActivePaymentData,
  GetInvestmentActivePaymentError,
  GetInvestmentActivePaymentResponse,
  CreateInvestmentPaymentIntentData,
  CreateInvestmentPaymentIntentError,
  CreateInvestmentPaymentIntentResponse,
  GetInvestmentPaymentsData,
  GetInvestmentPaymentsError,
  GetInvestmentPaymentsResponse,
  GetRoundByCursorData,
  GetRoundByCursorError,
  GetRoundByCursorResponse,
  CreateRoundData,
  CreateRoundError,
  CreateRoundResponse,
  GetRoundsByPageData,
  GetRoundsByPageError,
  GetRoundsByPageResponse,
  DeleteRoundData,
  DeleteRoundError,
  DeleteRoundResponse,
  GetRoundByIdData,
  GetRoundByIdError,
  GetRoundByIdResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Get account by user id
 * Fetches the account for the currently authenticated user.
 */
export const getAccount = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAccountResponse,
    GetAccountError,
    ThrowOnError
  >({
    ...options,
    url: "/account",
  });
};

/**
 * Create a account
 * Create a account.
 */
export const createAccount = <ThrowOnError extends boolean = false>(
  options: Options<CreateAccountData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    unknown,
    CreateAccountError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/account",
  });
};

/**
 * Get stripe identity
 * Get stripe identity for the currently authenticated account.
 */
export const getStripeIdentity = <ThrowOnError extends boolean = false>(
  options?: Options<GetStripeIdentityData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetStripeIdentityResponse,
    GetStripeIdentityError,
    ThrowOnError
  >({
    ...options,
    url: "/account/stripe-identity",
  });
};

/**
 * Get stripe identity verification session url
 * Get stripe identity verification session url for the currently authenticated account.
 */
export const getStripeIdentityVerificationSessionUrl = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetStripeIdentityVerificationSessionUrlData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    GetStripeIdentityVerificationSessionUrlResponse,
    GetStripeIdentityVerificationSessionUrlError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/account/stripe-identity",
  });
};

/**
 * Delete a account
 * Delete a account.
 */
export const deleteAccount = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteAccountData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteAccountResponse,
    DeleteAccountError,
    ThrowOnError
  >({
    ...options,
    url: "/account/{id}",
  });
};

/**
 * Update a account
 * Update a account.
 */
export const updateAccount = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateAccountResponse,
    UpdateAccountError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/account/{id}",
  });
};

/**
 * Get businesses
 * Get businesses.
 */
export const getAccountBusinesses = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountBusinessesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAccountBusinessesResponse,
    GetAccountBusinessesError,
    ThrowOnError
  >({
    ...options,
    url: "/account/{id}/businesses",
  });
};

/**
 * Create a business impression
 * Create a business impression.
 */
export const createBusinessImpression = <ThrowOnError extends boolean = false>(
  options?: Options<CreateBusinessImpressionData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateBusinessImpressionResponse,
    CreateBusinessImpressionError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/businesses/impressions",
  });
};

/**
 * Delete a business favourite
 * Delete a business favourite.
 */
export const deleteBusinessFavourite = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBusinessFavouriteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteBusinessFavouriteResponse,
    DeleteBusinessFavouriteError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/businesses/{id}/favourite",
  });
};

/**
 * Get a business favourite status
 * Get a business favourite status.
 */
export const getBusinessFavouriteStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBusinessFavouriteStatusData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessFavouriteStatusResponse,
    GetBusinessFavouriteStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/businesses/{id}/favourite",
  });
};

/**
 * Create a business favourite
 * Create a business favourite.
 */
export const createBusinessFavourite = <ThrowOnError extends boolean = false>(
  options: Options<CreateBusinessFavouriteData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateBusinessFavouriteResponse,
    CreateBusinessFavouriteError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/businesses/{id}/favourite",
  });
};

/**
 * Get a business favourite count
 * Get a business favourite count.
 */
export const getBusinessFavouriteCount = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessFavouriteCountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessFavouriteCountResponse,
    GetBusinessFavouriteCountError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/businesses/{id}/favourites",
  });
};

/**
 * Get a business impression count
 * Get a business impression count.
 */
export const getBusinessImpressionCount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBusinessImpressionCountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessImpressionCountResponse,
    GetBusinessImpressionCountError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/businesses/{id}/impressions",
  });
};

/**
 * Create a round favourite
 * Create a round favourite.
 */
export const createRoundFavourite = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoundFavouriteData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRoundFavouriteResponse,
    CreateRoundFavouriteError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/rounds/favourites",
  });
};

/**
 * Create a round impression
 * Create a round impression.
 */
export const createRoundImpression = <ThrowOnError extends boolean = false>(
  options?: Options<CreateRoundImpressionData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRoundImpressionResponse,
    CreateRoundImpressionError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/rounds/impressions",
  });
};

/**
 * Delete a round favourite
 * Delete a round favourite.
 */
export const deleteRoundFavourite = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRoundFavouriteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteRoundFavouriteResponse,
    DeleteRoundFavouriteError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/rounds/{id}/favourite",
  });
};

/**
 * Get a round favourite status
 * Get a round favourite status.
 */
export const getRoundFavouriteStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetRoundFavouriteStatusData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRoundFavouriteStatusResponse,
    GetRoundFavouriteStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/rounds/{id}/favourite",
  });
};

/**
 * Get a round favourite count
 * Get a round favourite count.
 */
export const getRoundFavouriteCount = <ThrowOnError extends boolean = false>(
  options: Options<GetRoundFavouriteCountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRoundFavouriteCountResponse,
    GetRoundFavouriteCountError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/rounds/{id}/favourites",
  });
};

/**
 * Get a round impression count
 * Get a round impression count.
 */
export const getRoundImpressionCount = <ThrowOnError extends boolean = false>(
  options: Options<GetRoundImpressionCountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRoundImpressionCountResponse,
    GetRoundImpressionCountError,
    ThrowOnError
  >({
    ...options,
    url: "/analytic/rounds/{id}/impressions",
  });
};

/**
 * Create a business
 * Create a business.
 */
export const createBusiness = <ThrowOnError extends boolean = false>(
  options: Options<CreateBusinessData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateBusinessResponse,
    CreateBusinessError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/business",
  });
};

/**
 * Get business stripe account
 * Get business stripe account.
 */
export const getBusinessStripeAccount = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessStripeAccountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessStripeAccountResponse,
    GetBusinessStripeAccountError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{businessId}/stripe",
  });
};

/**
 * Delete a business
 * Delete a business.
 */
export const deleteBusiness = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBusinessData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteBusinessResponse,
    DeleteBusinessError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}",
  });
};

/**
 * Get business by ID
 * Get business by ID.
 */
export const getBusinessById = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessByIdResponse,
    GetBusinessByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}",
  });
};

/**
 * Get business members
 * Get business members.
 */
export const getBusinessMembersByPage = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessMembersByPageData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessMembersByPageResponse,
    GetBusinessMembersByPageError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}/members/page",
  });
};

/**
 * Get round create requirements
 * Get round create requirements.
 */
export const getBusinessRoundCreateRequirements = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBusinessRoundCreateRequirementsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessRoundCreateRequirementsResponse,
    GetBusinessRoundCreateRequirementsError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}/requirements/round-create",
  });
};

/**
 * Get business member roles
 * Get all the roles created for this business.
 */
export const getBusinessMemberRoles = <ThrowOnError extends boolean = false>(
  options?: Options<GetBusinessMemberRolesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessMemberRolesResponse,
    GetBusinessMemberRolesError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}/roles",
  });
};

/**
 * Get rounds
 * Get rounds.
 */
export const getBusinessRoundsByCursor = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessRoundsByCursorData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessRoundsByCursorResponse,
    GetBusinessRoundsByCursorError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}/rounds",
  });
};

/**
 * Get rounds
 * Get rounds.
 */
export const getBusinessRoundsByPage = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessRoundsByPageData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetBusinessRoundsByPageResponse,
    GetBusinessRoundsByPageError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}/rounds/page",
  });
};

/**
 * Upsert business legal section
 * Upsert business legal section.
 */
export const upsertBusinessLegalSection = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpsertBusinessLegalSectionData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpsertBusinessLegalSectionResponse,
    UpsertBusinessLegalSectionError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/business/{id}/sections/legal",
  });
};

/**
 * Get Stripe dashboard url
 * Get Stripe dashboard url.
 */
export const getStripeDashboardUrl = <ThrowOnError extends boolean = false>(
  options: Options<GetStripeDashboardUrlData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetStripeDashboardUrlResponse,
    GetStripeDashboardUrlError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}/stripe-dashboard-url",
  });
};

/**
 * Onboard Stripe connected account
 * Onboard Stripe connected account.
 */
export const onboardStripeConnectedAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OnboardStripeConnectedAccountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OnboardStripeConnectedAccountResponse,
    OnboardStripeConnectedAccountError,
    ThrowOnError
  >({
    ...options,
    url: "/business/{id}/stripe-onboard",
  });
};

/**
 * Health check
 * Health check.
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckResponse,
    HealthCheckError,
    ThrowOnError
  >({
    ...options,
    url: "/health",
  });
};

/**
 * Get all industries
 * Get all industries.
 */
export const getAllIndustries = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllIndustriesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllIndustriesResponse,
    GetAllIndustriesError,
    ThrowOnError
  >({
    ...options,
    url: "/industries",
  });
};

/**
 * Create a round investment
 * Create a round investment.
 */
export const createRoundInvestment = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoundInvestmentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRoundInvestmentResponse,
    CreateRoundInvestmentError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/investments",
  });
};

/**
 * Get a round investment
 * Get a round investment.
 */
export const getInvestmentById = <ThrowOnError extends boolean = false>(
  options: Options<GetInvestmentByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetInvestmentByIdResponse,
    GetInvestmentByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/investments/{id}",
  });
};

/**
 * Get the active payment for an investment
 * Get the payment for the current investment that is either processing or succeeded.
 */
export const getInvestmentActivePayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetInvestmentActivePaymentData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetInvestmentActivePaymentResponse,
    GetInvestmentActivePaymentError,
    ThrowOnError
  >({
    ...options,
    url: "/investments/{id}/pay",
  });
};

/**
 * Create a stripe payment intent
 * Create a stripe payment intent for an investment.
 */
export const createInvestmentPaymentIntent = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateInvestmentPaymentIntentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateInvestmentPaymentIntentResponse,
    CreateInvestmentPaymentIntentError,
    ThrowOnError
  >({
    ...options,
    url: "/investments/{id}/pay",
  });
};

/**
 * Get a round investment payments
 * Get a round investment payments.
 */
export const getInvestmentPayments = <ThrowOnError extends boolean = false>(
  options: Options<GetInvestmentPaymentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetInvestmentPaymentsResponse,
    GetInvestmentPaymentsError,
    ThrowOnError
  >({
    ...options,
    url: "/investments/{id}/payments",
  });
};

/**
 * Get rounds by cursor
 * Get rounds by cursor.
 */
export const getRoundByCursor = <ThrowOnError extends boolean = false>(
  options?: Options<GetRoundByCursorData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRoundByCursorResponse,
    GetRoundByCursorError,
    ThrowOnError
  >({
    ...options,
    url: "/round",
  });
};

/**
 * Create a round
 * Create a round.
 */
export const createRound = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoundData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRoundResponse,
    CreateRoundError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/round",
  });
};

/**
 * Get rounds by page
 * Get rounds by page.
 */
export const getRoundsByPage = <ThrowOnError extends boolean = false>(
  options?: Options<GetRoundsByPageData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRoundsByPageResponse,
    GetRoundsByPageError,
    ThrowOnError
  >({
    ...options,
    url: "/round/page",
  });
};

/**
 * Delete a round
 * Delete a round.
 */
export const deleteRound = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRoundData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteRoundResponse,
    DeleteRoundError,
    ThrowOnError
  >({
    ...options,
    url: "/round/{id}",
  });
};

/**
 * Get round by ID
 * Get round by ID.
 */
export const getRoundById = <ThrowOnError extends boolean = false>(
  options: Options<GetRoundByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRoundByIdResponse,
    GetRoundByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/round/{id}",
  });
};
