// This file is auto-generated by @hey-api/openapi-ts

export type Account = {
    createdAt: Date;
    deletedAt: (Date) | null;
    firstName: string;
    id: number;
    lastName: string;
    updatedAt: (Date) | null;
    userId: string;
};

export type CreateAccountParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    firstName: string;
    lastName: string;
    userId: string;
};

export type CreateDutchDynamicRoundParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    dutchDynamicRound: DutchDynamicRoundParams;
    round: CreateRoundParams;
};

export type CreateFixedTotalRoundParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    round: CreateRoundParams;
};

export type CreateInvestmentParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    amount: number;
    investorId: number;
    roundId: number;
    status: 'pending' | 'accepted' | 'rejected' | 'withdrawn';
};

export type status = 'pending' | 'accepted' | 'rejected' | 'withdrawn';

export const status = {
    PENDING: 'pending',
    ACCEPTED: 'accepted',
    REJECTED: 'rejected',
    WITHDRAWN: 'withdrawn'
} as const;

export type CreatePartialTotalRoundParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    partialTotalRound: PartialTotalRoundParams;
    round: CreateRoundParams;
};

export type CreateRegularDynamicRoundParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    regularDynamicRound: RegularDynamicRoundParams;
    round: CreateRoundParams;
};

export type CreateRoundParams = {
    beginsAt: Date;
    endsAt: Date;
    percentageOffered: number;
    percentageValue: number;
    status: 'active' | 'successful' | 'failed';
    valueCurrency: 'USD' | 'GBP' | 'EUR' | 'CAD' | 'AUD' | 'JPY';
    ventureId: number;
};

export type status2 = 'active' | 'successful' | 'failed';

export const status2 = {
    ACTIVE: 'active',
    SUCCESSFUL: 'successful',
    FAILED: 'failed'
} as const;

export type valueCurrency = 'USD' | 'GBP' | 'EUR' | 'CAD' | 'AUD' | 'JPY';

export const valueCurrency = {
    USD: 'USD',
    GBP: 'GBP',
    EUR: 'EUR',
    CAD: 'CAD',
    AUD: 'AUD',
    JPY: 'JPY'
} as const;

export type CreateVentureParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description: string;
    name: string;
    ownerAccountId: number;
};

export type DutchDynamicRound = {
    createdAt: Date;
    deletedAt: (Date) | null;
    round: Round;
    roundId: number;
    updatedAt: (Date) | null;
    valuationDollarDropRate: number;
    valuationDropIntervalDays: number;
    valuationStopLoss: number;
};

export type DutchDynamicRoundParams = {
    valuationDollarDropRate: number;
    valuationDropIntervalDays: number;
    valuationStopLoss: number;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type FixedTotalRound = {
    createdAt: Date;
    deletedAt: (Date) | null;
    round: Round;
    updatedAt: (Date) | null;
};

export type GetCursorPaginatedDutchDynamicRoundsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    dutchDynamicRounds: Array<DutchDynamicRound> | null;
    hasMore: boolean;
    message: string;
    nextCursor: (number) | null;
};

export type GetCursorPaginatedFixedTotalRoundsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    fixedTotalRounds: Array<FixedTotalRound> | null;
    hasMore: boolean;
    message: string;
    nextCursor: (number) | null;
};

export type GetCursorPaginatedPartialTotalRoundsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    hasMore: boolean;
    message: string;
    nextCursor: (number) | null;
    partialTotalRounds: Array<PartialTotalRound> | null;
};

export type GetCursorPaginatedRegularDynamicRoundsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    hasMore: boolean;
    message: string;
    nextCursor: (number) | null;
    regularDynamicRounds: Array<RegularDynamicRound> | null;
};

export type GetCursorPaginatedRoundInvestmentsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    hasMore: boolean;
    investments: Array<RoundInvestment> | null;
    message: string;
    nextCursor: (number) | null;
};

export type GetCursorPaginatedVenturesOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    hasMore: boolean;
    message: string;
    nextCursor: (number) | null;
    ventures: Array<Venture> | null;
};

export type GetOffsetPaginatedDutchDynamicRoundsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    dutchDynamicRounds: Array<DutchDynamicRound> | null;
    hasMore: boolean;
    message: string;
};

export type GetOffsetPaginatedFixedTotalRoundsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    fixedTotalRounds: Array<FixedTotalRound> | null;
    hasMore: boolean;
    message: string;
};

export type GetOffsetPaginatedPartialTotalRoundsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    hasMore: boolean;
    message: string;
    partialTotalRounds: Array<PartialTotalRound> | null;
};

export type GetOffsetPaginatedRegularDynamicRoundsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    hasMore: boolean;
    message: string;
    regularDynamicRounds: Array<RegularDynamicRound> | null;
};

export type GetOffsetPaginatedRoundInvestmentsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    hasMore: boolean;
    investments: Array<RoundInvestment> | null;
    message: string;
};

export type GetOffsetPaginatedVenturesOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    hasMore: boolean;
    message: string;
    ventures: Array<Venture> | null;
};

export type MessageResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type PartialTotalRound = {
    createdAt: Date;
    deletedAt: (Date) | null;
    investorCount: number;
    round: Round;
    roundId: number;
    updatedAt: (Date) | null;
};

export type PartialTotalRoundParams = {
    investorCount: number;
};

export type RegularDynamicRound = {
    createdAt: Date;
    daysExtendOnBid: number;
    deletedAt: (Date) | null;
    round: Round;
    roundId: number;
    updatedAt: (Date) | null;
};

export type RegularDynamicRoundParams = {
    daysExtendOnBid: number;
};

export type Round = {
    beginsAt: Date;
    createdAt: Date;
    deletedAt: (Date) | null;
    endsAt: Date;
    id: number;
    percentageOffered: number;
    percentageValue: number;
    status: 'active' | 'successful' | 'failed';
    updatedAt: (Date) | null;
    valueCurrency: 'USD' | 'GBP' | 'EUR' | 'CAD' | 'AUD' | 'JPY';
    ventureId: number;
};

export type RoundInvestment = {
    amount: number;
    createdAt: Date;
    deletedAt: (Date) | null;
    id: number;
    investor: Account;
    investorId: number;
    round: Round;
    roundId: number;
    status: 'pending' | 'accepted' | 'rejected' | 'withdrawn';
    updatedAt: (Date) | null;
};

export type SingleAccountResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    account: Account;
    message: string;
};

export type SingleDutchDynamicRoundResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
    round: DutchDynamicRound;
};

export type SingleFixedTotalRoundResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
    round: FixedTotalRound;
};

export type SinglePartialTotalRoundResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
    round: PartialTotalRound;
};

export type SingleRegularDynamicRoundResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
    round: RegularDynamicRound;
};

export type SingleRoundInvestmentResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    investment: RoundInvestment;
    message: string;
};

export type SingleVentureResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
    venture: Venture;
};

export type UpdateAccountParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    firstName: string;
    lastName: string;
};

export type UpdateVentureParams = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description: string;
    name: string;
};

export type Venture = {
    createdAt: Date;
    deletedAt: (Date) | null;
    description: string;
    id: number;
    name: string;
    ownerAccountId: number;
    updatedAt: (Date) | null;
};

export type CreateAccountData = {
    body: CreateAccountParams;
};

export type CreateAccountResponse = (SingleAccountResponseBody);

export type CreateAccountError = (ErrorModel);

export type DeleteAccountData = {
    path: {
        id: number;
    };
};

export type DeleteAccountResponse = (MessageResponse);

export type DeleteAccountError = (ErrorModel);

export type GetAccountByIdData = {
    path: {
        id: number;
    };
};

export type GetAccountByIdResponse = (SingleAccountResponseBody);

export type GetAccountByIdError = (ErrorModel);

export type UpdateAccountData = {
    body: UpdateAccountParams;
    path: {
        id: number;
    };
};

export type UpdateAccountResponse = (SingleAccountResponseBody);

export type UpdateAccountError = (ErrorModel);

export type CreateRoundInvestmentData = {
    body: CreateInvestmentParams;
};

export type CreateRoundInvestmentResponse = (SingleRoundInvestmentResponseBody);

export type CreateRoundInvestmentError = (ErrorModel);

export type GetAccountRoundInvestmentsCursorData = {
    path: {
        id: number;
    };
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetAccountRoundInvestmentsCursorResponse = (GetCursorPaginatedRoundInvestmentsOutputBody);

export type GetAccountRoundInvestmentsCursorError = (ErrorModel);

export type GetRoundInvestmentsOffsetData = {
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetRoundInvestmentsOffsetResponse = (GetOffsetPaginatedRoundInvestmentsOutputBody);

export type GetRoundInvestmentsOffsetError = (ErrorModel);

export type DeleteRoundInvestmentData = {
    path: {
        id: number;
        investmentId: number;
    };
};

export type DeleteRoundInvestmentResponse = (string);

export type DeleteRoundInvestmentError = (ErrorModel);

export type WithdrawRoundInvestmentData = {
    path: {
        id: number;
        investmentId: number;
    };
};

export type WithdrawRoundInvestmentResponse = (string);

export type WithdrawRoundInvestmentError = (ErrorModel);

export type GetAccountVenturesData = {
    path: {
        id: number;
    };
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetAccountVenturesResponse = (GetCursorPaginatedVenturesOutputBody);

export type GetAccountVenturesError = (ErrorModel);

export type HealthCheckResponse = (MessageResponse);

export type HealthCheckError = (ErrorModel);

export type CreateDutchDynamicRoundData = {
    body: CreateDutchDynamicRoundParams;
};

export type CreateDutchDynamicRoundResponse = (SingleDutchDynamicRoundResponseBody);

export type CreateDutchDynamicRoundError = (ErrorModel);

export type GetAllDutchDynamicRoundsCursorData = {
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetAllDutchDynamicRoundsCursorResponse = (GetCursorPaginatedDutchDynamicRoundsOutputBody);

export type GetAllDutchDynamicRoundsCursorError = (ErrorModel);

export type GetAllDutchDynamicRoundsOffsetData = {
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetAllDutchDynamicRoundsOffsetResponse = (GetOffsetPaginatedDutchDynamicRoundsOutputBody);

export type GetAllDutchDynamicRoundsOffsetError = (ErrorModel);

export type DeleteDutchDynamicRoundData = {
    path: {
        id: number;
    };
};

export type DeleteDutchDynamicRoundResponse = (MessageResponse);

export type DeleteDutchDynamicRoundError = (ErrorModel);

export type GetDutchDynamicRoundByIdData = {
    path: {
        id: number;
    };
};

export type GetDutchDynamicRoundByIdResponse = (SingleDutchDynamicRoundResponseBody);

export type GetDutchDynamicRoundByIdError = (ErrorModel);

export type CreateRegularDynamicRoundData = {
    body: CreateRegularDynamicRoundParams;
};

export type CreateRegularDynamicRoundResponse = (SingleRegularDynamicRoundResponseBody);

export type CreateRegularDynamicRoundError = (ErrorModel);

export type GetAllRegularDynamicRoundsCursorData = {
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetAllRegularDynamicRoundsCursorResponse = (GetCursorPaginatedRegularDynamicRoundsOutputBody);

export type GetAllRegularDynamicRoundsCursorError = (ErrorModel);

export type GetAllRegularDynamicRoundsOffsetData = {
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetAllRegularDynamicRoundsOffsetResponse = (GetOffsetPaginatedRegularDynamicRoundsOutputBody);

export type GetAllRegularDynamicRoundsOffsetError = (ErrorModel);

export type DeleteRegularDynamicRoundData = {
    path: {
        id: number;
    };
};

export type DeleteRegularDynamicRoundResponse = (MessageResponse);

export type DeleteRegularDynamicRoundError = (ErrorModel);

export type GetRegularDynamicRoundByIdData = {
    path: {
        id: number;
    };
};

export type GetRegularDynamicRoundByIdResponse = (SingleRegularDynamicRoundResponseBody);

export type GetRegularDynamicRoundByIdError = (ErrorModel);

export type CreateFixedTotalRoundData = {
    body: CreateFixedTotalRoundParams;
};

export type CreateFixedTotalRoundResponse = (SingleFixedTotalRoundResponseBody);

export type CreateFixedTotalRoundError = (ErrorModel);

export type GetAllFixedTotalRoundsCursorData = {
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetAllFixedTotalRoundsCursorResponse = (GetCursorPaginatedFixedTotalRoundsOutputBody);

export type GetAllFixedTotalRoundsCursorError = (ErrorModel);

export type GetAllFixedTotalRoundsOffsetData = {
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetAllFixedTotalRoundsOffsetResponse = (GetOffsetPaginatedFixedTotalRoundsOutputBody);

export type GetAllFixedTotalRoundsOffsetError = (ErrorModel);

export type DeleteFixedTotalRoundData = {
    path: {
        id: number;
    };
};

export type DeleteFixedTotalRoundResponse = (MessageResponse);

export type DeleteFixedTotalRoundError = (ErrorModel);

export type GetFixedTotalRoundByIdData = {
    path: {
        id: number;
    };
};

export type GetFixedTotalRoundByIdResponse = (SingleFixedTotalRoundResponseBody);

export type GetFixedTotalRoundByIdError = (ErrorModel);

export type CreatePartialTotalRoundData = {
    body: CreatePartialTotalRoundParams;
};

export type CreatePartialTotalRoundResponse = (SinglePartialTotalRoundResponseBody);

export type CreatePartialTotalRoundError = (ErrorModel);

export type GetAllPartialTotalRoundsCursorData = {
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetAllPartialTotalRoundsCursorResponse = (GetCursorPaginatedPartialTotalRoundsOutputBody);

export type GetAllPartialTotalRoundsCursorError = (ErrorModel);

export type GetAllPartialTotalRoundsOffsetData = {
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetAllPartialTotalRoundsOffsetResponse = (GetOffsetPaginatedPartialTotalRoundsOutputBody);

export type GetAllPartialTotalRoundsOffsetError = (ErrorModel);

export type DeletePartialTotalRoundData = {
    path: {
        id: number;
    };
};

export type DeletePartialTotalRoundResponse = (MessageResponse);

export type DeletePartialTotalRoundError = (ErrorModel);

export type GetPartialTotalRoundByIdData = {
    path: {
        id: number;
    };
};

export type GetPartialTotalRoundByIdResponse = (SinglePartialTotalRoundResponseBody);

export type GetPartialTotalRoundByIdError = (ErrorModel);

export type GetRoundRoundInvestmentsCursorData = {
    path: {
        id: number;
    };
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetRoundRoundInvestmentsCursorResponse = (GetCursorPaginatedRoundInvestmentsOutputBody);

export type GetRoundRoundInvestmentsCursorError = (ErrorModel);

export type GetRoundRoundInvestmentsOffsetData = {
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetRoundRoundInvestmentsOffsetResponse = (GetOffsetPaginatedRoundInvestmentsOutputBody);

export type GetRoundRoundInvestmentsOffsetError = (ErrorModel);

export type AcceptRoundInvestmentData = {
    path: {
        id: number;
        investmentId: number;
    };
};

export type AcceptRoundInvestmentResponse = (string);

export type AcceptRoundInvestmentError = (ErrorModel);

export type GetUserAccountData = {
    path: {
        userId: string;
    };
};

export type GetUserAccountResponse = (SingleAccountResponseBody);

export type GetUserAccountError = (ErrorModel);

export type CreateVentureData = {
    body: CreateVentureParams;
};

export type CreateVentureResponse = (SingleVentureResponseBody);

export type CreateVentureError = (ErrorModel);

export type GetAllVenturesCursorData = {
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetAllVenturesCursorResponse = (GetCursorPaginatedVenturesOutputBody);

export type GetAllVenturesCursorError = (ErrorModel);

export type GetAllVenturesOffsetData = {
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetAllVenturesOffsetResponse = (GetOffsetPaginatedVenturesOutputBody);

export type GetAllVenturesOffsetError = (ErrorModel);

export type DeleteVentureData = {
    path: {
        id: number;
    };
};

export type DeleteVentureResponse = (MessageResponse);

export type DeleteVentureError = (ErrorModel);

export type GetVentureByIdData = {
    path: {
        id: number;
    };
};

export type GetVentureByIdResponse = (SingleVentureResponseBody);

export type GetVentureByIdError = (ErrorModel);

export type UpdateVentureData = {
    body: UpdateVentureParams;
    path: {
        id: number;
    };
};

export type UpdateVentureResponse = (SingleVentureResponseBody);

export type UpdateVentureError = (ErrorModel);

export type GetVentureRoundInvestmentsCursorData = {
    path: {
        id: number;
    };
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetVentureRoundInvestmentsCursorResponse = (GetCursorPaginatedRoundInvestmentsOutputBody);

export type GetVentureRoundInvestmentsCursorError = (ErrorModel);

export type GetVentureRoundInvestmentsOffsetData = {
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetVentureRoundInvestmentsOffsetResponse = (GetOffsetPaginatedRoundInvestmentsOutputBody);

export type GetVentureRoundInvestmentsOffsetError = (ErrorModel);

export type GetVentureDutchDynamicRoundsCursorData = {
    path: {
        id: number;
    };
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetVentureDutchDynamicRoundsCursorResponse = (GetCursorPaginatedDutchDynamicRoundsOutputBody);

export type GetVentureDutchDynamicRoundsCursorError = (ErrorModel);

export type GetVentureDutchDynamicRoundsOffsetData = {
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetVentureDutchDynamicRoundsOffsetResponse = (GetOffsetPaginatedDutchDynamicRoundsOutputBody);

export type GetVentureDutchDynamicRoundsOffsetError = (ErrorModel);

export type GetVentureRegularDynamicRoundsCursorData = {
    path: {
        id: number;
    };
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetVentureRegularDynamicRoundsCursorResponse = (GetCursorPaginatedRegularDynamicRoundsOutputBody);

export type GetVentureRegularDynamicRoundsCursorError = (ErrorModel);

export type GetVentureRegularDynamicRoundsOffsetData = {
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetVentureRegularDynamicRoundsOffsetResponse = (GetOffsetPaginatedRegularDynamicRoundsOutputBody);

export type GetVentureRegularDynamicRoundsOffsetError = (ErrorModel);

export type GetVentureFixedTotalRoundsCursorData = {
    path: {
        id: number;
    };
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetVentureFixedTotalRoundsCursorResponse = (GetCursorPaginatedFixedTotalRoundsOutputBody);

export type GetVentureFixedTotalRoundsCursorError = (ErrorModel);

export type GetVentureFixedTotalRoundsOffsetData = {
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetVentureFixedTotalRoundsOffsetResponse = (GetOffsetPaginatedFixedTotalRoundsOutputBody);

export type GetVentureFixedTotalRoundsOffsetError = (ErrorModel);

export type GetVenturePartialTotalRoundsCursorData = {
    path: {
        id: number;
    };
    query?: {
        cursor?: number;
        limit?: number;
    };
};

export type GetVenturePartialTotalRoundsCursorResponse = (GetCursorPaginatedPartialTotalRoundsOutputBody);

export type GetVenturePartialTotalRoundsCursorError = (ErrorModel);

export type GetVenturePartialTotalRoundsOffsetData = {
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
};

export type GetVenturePartialTotalRoundsOffsetResponse = (GetOffsetPaginatedPartialTotalRoundsOutputBody);

export type GetVenturePartialTotalRoundsOffsetError = (ErrorModel);

export type CreateAccountResponseTransformer = (data: any) => Promise<CreateAccountResponse>;

export type SingleAccountResponseBodyModelResponseTransformer = (data: any) => SingleAccountResponseBody;

export type AccountModelResponseTransformer = (data: any) => Account;

export const AccountModelResponseTransformer: AccountModelResponseTransformer = data => {
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    if (data?.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const SingleAccountResponseBodyModelResponseTransformer: SingleAccountResponseBodyModelResponseTransformer = data => {
    if (data?.account) {
        AccountModelResponseTransformer(data.account);
    }
    return data;
};

export const CreateAccountResponseTransformer: CreateAccountResponseTransformer = async (data) => {
    SingleAccountResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetAccountByIdResponseTransformer = (data: any) => Promise<GetAccountByIdResponse>;

export const GetAccountByIdResponseTransformer: GetAccountByIdResponseTransformer = async (data) => {
    SingleAccountResponseBodyModelResponseTransformer(data);
    return data;
};

export type UpdateAccountResponseTransformer = (data: any) => Promise<UpdateAccountResponse>;

export const UpdateAccountResponseTransformer: UpdateAccountResponseTransformer = async (data) => {
    SingleAccountResponseBodyModelResponseTransformer(data);
    return data;
};

export type CreateRoundInvestmentResponseTransformer = (data: any) => Promise<CreateRoundInvestmentResponse>;

export type SingleRoundInvestmentResponseBodyModelResponseTransformer = (data: any) => SingleRoundInvestmentResponseBody;

export type RoundInvestmentModelResponseTransformer = (data: any) => RoundInvestment;

export type RoundModelResponseTransformer = (data: any) => Round;

export const RoundModelResponseTransformer: RoundModelResponseTransformer = data => {
    if (data?.beginsAt) {
        data.beginsAt = new Date(data.beginsAt);
    }
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    if (data?.endsAt) {
        data.endsAt = new Date(data.endsAt);
    }
    if (data?.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const RoundInvestmentModelResponseTransformer: RoundInvestmentModelResponseTransformer = data => {
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    if (data?.investor) {
        AccountModelResponseTransformer(data.investor);
    }
    if (data?.round) {
        RoundModelResponseTransformer(data.round);
    }
    if (data?.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const SingleRoundInvestmentResponseBodyModelResponseTransformer: SingleRoundInvestmentResponseBodyModelResponseTransformer = data => {
    if (data?.investment) {
        RoundInvestmentModelResponseTransformer(data.investment);
    }
    return data;
};

export const CreateRoundInvestmentResponseTransformer: CreateRoundInvestmentResponseTransformer = async (data) => {
    SingleRoundInvestmentResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetAccountRoundInvestmentsCursorResponseTransformer = (data: any) => Promise<GetAccountRoundInvestmentsCursorResponse>;

export type GetCursorPaginatedRoundInvestmentsOutputBodyModelResponseTransformer = (data: any) => GetCursorPaginatedRoundInvestmentsOutputBody;

export const GetCursorPaginatedRoundInvestmentsOutputBodyModelResponseTransformer: GetCursorPaginatedRoundInvestmentsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.investments)) {
        data.investments.forEach(RoundInvestmentModelResponseTransformer);
    }
    return data;
};

export const GetAccountRoundInvestmentsCursorResponseTransformer: GetAccountRoundInvestmentsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedRoundInvestmentsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetRoundInvestmentsOffsetResponseTransformer = (data: any) => Promise<GetRoundInvestmentsOffsetResponse>;

export type GetOffsetPaginatedRoundInvestmentsOutputBodyModelResponseTransformer = (data: any) => GetOffsetPaginatedRoundInvestmentsOutputBody;

export const GetOffsetPaginatedRoundInvestmentsOutputBodyModelResponseTransformer: GetOffsetPaginatedRoundInvestmentsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.investments)) {
        data.investments.forEach(RoundInvestmentModelResponseTransformer);
    }
    return data;
};

export const GetRoundInvestmentsOffsetResponseTransformer: GetRoundInvestmentsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedRoundInvestmentsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetAccountVenturesResponseTransformer = (data: any) => Promise<GetAccountVenturesResponse>;

export type GetCursorPaginatedVenturesOutputBodyModelResponseTransformer = (data: any) => GetCursorPaginatedVenturesOutputBody;

export type VentureModelResponseTransformer = (data: any) => Venture;

export const VentureModelResponseTransformer: VentureModelResponseTransformer = data => {
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    if (data?.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const GetCursorPaginatedVenturesOutputBodyModelResponseTransformer: GetCursorPaginatedVenturesOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.ventures)) {
        data.ventures.forEach(VentureModelResponseTransformer);
    }
    return data;
};

export const GetAccountVenturesResponseTransformer: GetAccountVenturesResponseTransformer = async (data) => {
    GetCursorPaginatedVenturesOutputBodyModelResponseTransformer(data);
    return data;
};

export type CreateDutchDynamicRoundResponseTransformer = (data: any) => Promise<CreateDutchDynamicRoundResponse>;

export type SingleDutchDynamicRoundResponseBodyModelResponseTransformer = (data: any) => SingleDutchDynamicRoundResponseBody;

export type DutchDynamicRoundModelResponseTransformer = (data: any) => DutchDynamicRound;

export const DutchDynamicRoundModelResponseTransformer: DutchDynamicRoundModelResponseTransformer = data => {
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    if (data?.round) {
        RoundModelResponseTransformer(data.round);
    }
    if (data?.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const SingleDutchDynamicRoundResponseBodyModelResponseTransformer: SingleDutchDynamicRoundResponseBodyModelResponseTransformer = data => {
    if (data?.round) {
        DutchDynamicRoundModelResponseTransformer(data.round);
    }
    return data;
};

export const CreateDutchDynamicRoundResponseTransformer: CreateDutchDynamicRoundResponseTransformer = async (data) => {
    SingleDutchDynamicRoundResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetAllDutchDynamicRoundsCursorResponseTransformer = (data: any) => Promise<GetAllDutchDynamicRoundsCursorResponse>;

export type GetCursorPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer = (data: any) => GetCursorPaginatedDutchDynamicRoundsOutputBody;

export const GetCursorPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer: GetCursorPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.dutchDynamicRounds)) {
        data.dutchDynamicRounds.forEach(DutchDynamicRoundModelResponseTransformer);
    }
    return data;
};

export const GetAllDutchDynamicRoundsCursorResponseTransformer: GetAllDutchDynamicRoundsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetAllDutchDynamicRoundsOffsetResponseTransformer = (data: any) => Promise<GetAllDutchDynamicRoundsOffsetResponse>;

export type GetOffsetPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer = (data: any) => GetOffsetPaginatedDutchDynamicRoundsOutputBody;

export const GetOffsetPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer: GetOffsetPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.dutchDynamicRounds)) {
        data.dutchDynamicRounds.forEach(DutchDynamicRoundModelResponseTransformer);
    }
    return data;
};

export const GetAllDutchDynamicRoundsOffsetResponseTransformer: GetAllDutchDynamicRoundsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetDutchDynamicRoundByIdResponseTransformer = (data: any) => Promise<GetDutchDynamicRoundByIdResponse>;

export const GetDutchDynamicRoundByIdResponseTransformer: GetDutchDynamicRoundByIdResponseTransformer = async (data) => {
    SingleDutchDynamicRoundResponseBodyModelResponseTransformer(data);
    return data;
};

export type CreateRegularDynamicRoundResponseTransformer = (data: any) => Promise<CreateRegularDynamicRoundResponse>;

export type SingleRegularDynamicRoundResponseBodyModelResponseTransformer = (data: any) => SingleRegularDynamicRoundResponseBody;

export type RegularDynamicRoundModelResponseTransformer = (data: any) => RegularDynamicRound;

export const RegularDynamicRoundModelResponseTransformer: RegularDynamicRoundModelResponseTransformer = data => {
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    if (data?.round) {
        RoundModelResponseTransformer(data.round);
    }
    if (data?.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const SingleRegularDynamicRoundResponseBodyModelResponseTransformer: SingleRegularDynamicRoundResponseBodyModelResponseTransformer = data => {
    if (data?.round) {
        RegularDynamicRoundModelResponseTransformer(data.round);
    }
    return data;
};

export const CreateRegularDynamicRoundResponseTransformer: CreateRegularDynamicRoundResponseTransformer = async (data) => {
    SingleRegularDynamicRoundResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetAllRegularDynamicRoundsCursorResponseTransformer = (data: any) => Promise<GetAllRegularDynamicRoundsCursorResponse>;

export type GetCursorPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer = (data: any) => GetCursorPaginatedRegularDynamicRoundsOutputBody;

export const GetCursorPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer: GetCursorPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.regularDynamicRounds)) {
        data.regularDynamicRounds.forEach(RegularDynamicRoundModelResponseTransformer);
    }
    return data;
};

export const GetAllRegularDynamicRoundsCursorResponseTransformer: GetAllRegularDynamicRoundsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetAllRegularDynamicRoundsOffsetResponseTransformer = (data: any) => Promise<GetAllRegularDynamicRoundsOffsetResponse>;

export type GetOffsetPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer = (data: any) => GetOffsetPaginatedRegularDynamicRoundsOutputBody;

export const GetOffsetPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer: GetOffsetPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.regularDynamicRounds)) {
        data.regularDynamicRounds.forEach(RegularDynamicRoundModelResponseTransformer);
    }
    return data;
};

export const GetAllRegularDynamicRoundsOffsetResponseTransformer: GetAllRegularDynamicRoundsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetRegularDynamicRoundByIdResponseTransformer = (data: any) => Promise<GetRegularDynamicRoundByIdResponse>;

export const GetRegularDynamicRoundByIdResponseTransformer: GetRegularDynamicRoundByIdResponseTransformer = async (data) => {
    SingleRegularDynamicRoundResponseBodyModelResponseTransformer(data);
    return data;
};

export type CreateFixedTotalRoundResponseTransformer = (data: any) => Promise<CreateFixedTotalRoundResponse>;

export type SingleFixedTotalRoundResponseBodyModelResponseTransformer = (data: any) => SingleFixedTotalRoundResponseBody;

export type FixedTotalRoundModelResponseTransformer = (data: any) => FixedTotalRound;

export const FixedTotalRoundModelResponseTransformer: FixedTotalRoundModelResponseTransformer = data => {
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    if (data?.round) {
        RoundModelResponseTransformer(data.round);
    }
    if (data?.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const SingleFixedTotalRoundResponseBodyModelResponseTransformer: SingleFixedTotalRoundResponseBodyModelResponseTransformer = data => {
    if (data?.round) {
        FixedTotalRoundModelResponseTransformer(data.round);
    }
    return data;
};

export const CreateFixedTotalRoundResponseTransformer: CreateFixedTotalRoundResponseTransformer = async (data) => {
    SingleFixedTotalRoundResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetAllFixedTotalRoundsCursorResponseTransformer = (data: any) => Promise<GetAllFixedTotalRoundsCursorResponse>;

export type GetCursorPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer = (data: any) => GetCursorPaginatedFixedTotalRoundsOutputBody;

export const GetCursorPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer: GetCursorPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.fixedTotalRounds)) {
        data.fixedTotalRounds.forEach(FixedTotalRoundModelResponseTransformer);
    }
    return data;
};

export const GetAllFixedTotalRoundsCursorResponseTransformer: GetAllFixedTotalRoundsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetAllFixedTotalRoundsOffsetResponseTransformer = (data: any) => Promise<GetAllFixedTotalRoundsOffsetResponse>;

export type GetOffsetPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer = (data: any) => GetOffsetPaginatedFixedTotalRoundsOutputBody;

export const GetOffsetPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer: GetOffsetPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.fixedTotalRounds)) {
        data.fixedTotalRounds.forEach(FixedTotalRoundModelResponseTransformer);
    }
    return data;
};

export const GetAllFixedTotalRoundsOffsetResponseTransformer: GetAllFixedTotalRoundsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetFixedTotalRoundByIdResponseTransformer = (data: any) => Promise<GetFixedTotalRoundByIdResponse>;

export const GetFixedTotalRoundByIdResponseTransformer: GetFixedTotalRoundByIdResponseTransformer = async (data) => {
    SingleFixedTotalRoundResponseBodyModelResponseTransformer(data);
    return data;
};

export type CreatePartialTotalRoundResponseTransformer = (data: any) => Promise<CreatePartialTotalRoundResponse>;

export type SinglePartialTotalRoundResponseBodyModelResponseTransformer = (data: any) => SinglePartialTotalRoundResponseBody;

export type PartialTotalRoundModelResponseTransformer = (data: any) => PartialTotalRound;

export const PartialTotalRoundModelResponseTransformer: PartialTotalRoundModelResponseTransformer = data => {
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    if (data?.round) {
        RoundModelResponseTransformer(data.round);
    }
    if (data?.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const SinglePartialTotalRoundResponseBodyModelResponseTransformer: SinglePartialTotalRoundResponseBodyModelResponseTransformer = data => {
    if (data?.round) {
        PartialTotalRoundModelResponseTransformer(data.round);
    }
    return data;
};

export const CreatePartialTotalRoundResponseTransformer: CreatePartialTotalRoundResponseTransformer = async (data) => {
    SinglePartialTotalRoundResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetAllPartialTotalRoundsCursorResponseTransformer = (data: any) => Promise<GetAllPartialTotalRoundsCursorResponse>;

export type GetCursorPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer = (data: any) => GetCursorPaginatedPartialTotalRoundsOutputBody;

export const GetCursorPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer: GetCursorPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.partialTotalRounds)) {
        data.partialTotalRounds.forEach(PartialTotalRoundModelResponseTransformer);
    }
    return data;
};

export const GetAllPartialTotalRoundsCursorResponseTransformer: GetAllPartialTotalRoundsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetAllPartialTotalRoundsOffsetResponseTransformer = (data: any) => Promise<GetAllPartialTotalRoundsOffsetResponse>;

export type GetOffsetPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer = (data: any) => GetOffsetPaginatedPartialTotalRoundsOutputBody;

export const GetOffsetPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer: GetOffsetPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.partialTotalRounds)) {
        data.partialTotalRounds.forEach(PartialTotalRoundModelResponseTransformer);
    }
    return data;
};

export const GetAllPartialTotalRoundsOffsetResponseTransformer: GetAllPartialTotalRoundsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetPartialTotalRoundByIdResponseTransformer = (data: any) => Promise<GetPartialTotalRoundByIdResponse>;

export const GetPartialTotalRoundByIdResponseTransformer: GetPartialTotalRoundByIdResponseTransformer = async (data) => {
    SinglePartialTotalRoundResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetRoundRoundInvestmentsCursorResponseTransformer = (data: any) => Promise<GetRoundRoundInvestmentsCursorResponse>;

export const GetRoundRoundInvestmentsCursorResponseTransformer: GetRoundRoundInvestmentsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedRoundInvestmentsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetRoundRoundInvestmentsOffsetResponseTransformer = (data: any) => Promise<GetRoundRoundInvestmentsOffsetResponse>;

export const GetRoundRoundInvestmentsOffsetResponseTransformer: GetRoundRoundInvestmentsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedRoundInvestmentsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetUserAccountResponseTransformer = (data: any) => Promise<GetUserAccountResponse>;

export const GetUserAccountResponseTransformer: GetUserAccountResponseTransformer = async (data) => {
    SingleAccountResponseBodyModelResponseTransformer(data);
    return data;
};

export type CreateVentureResponseTransformer = (data: any) => Promise<CreateVentureResponse>;

export type SingleVentureResponseBodyModelResponseTransformer = (data: any) => SingleVentureResponseBody;

export const SingleVentureResponseBodyModelResponseTransformer: SingleVentureResponseBodyModelResponseTransformer = data => {
    if (data?.venture) {
        VentureModelResponseTransformer(data.venture);
    }
    return data;
};

export const CreateVentureResponseTransformer: CreateVentureResponseTransformer = async (data) => {
    SingleVentureResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetAllVenturesCursorResponseTransformer = (data: any) => Promise<GetAllVenturesCursorResponse>;

export const GetAllVenturesCursorResponseTransformer: GetAllVenturesCursorResponseTransformer = async (data) => {
    GetCursorPaginatedVenturesOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetAllVenturesOffsetResponseTransformer = (data: any) => Promise<GetAllVenturesOffsetResponse>;

export type GetOffsetPaginatedVenturesOutputBodyModelResponseTransformer = (data: any) => GetOffsetPaginatedVenturesOutputBody;

export const GetOffsetPaginatedVenturesOutputBodyModelResponseTransformer: GetOffsetPaginatedVenturesOutputBodyModelResponseTransformer = data => {
    if (Array.isArray(data?.ventures)) {
        data.ventures.forEach(VentureModelResponseTransformer);
    }
    return data;
};

export const GetAllVenturesOffsetResponseTransformer: GetAllVenturesOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedVenturesOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureByIdResponseTransformer = (data: any) => Promise<GetVentureByIdResponse>;

export const GetVentureByIdResponseTransformer: GetVentureByIdResponseTransformer = async (data) => {
    SingleVentureResponseBodyModelResponseTransformer(data);
    return data;
};

export type UpdateVentureResponseTransformer = (data: any) => Promise<UpdateVentureResponse>;

export const UpdateVentureResponseTransformer: UpdateVentureResponseTransformer = async (data) => {
    SingleVentureResponseBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureRoundInvestmentsCursorResponseTransformer = (data: any) => Promise<GetVentureRoundInvestmentsCursorResponse>;

export const GetVentureRoundInvestmentsCursorResponseTransformer: GetVentureRoundInvestmentsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedRoundInvestmentsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureRoundInvestmentsOffsetResponseTransformer = (data: any) => Promise<GetVentureRoundInvestmentsOffsetResponse>;

export const GetVentureRoundInvestmentsOffsetResponseTransformer: GetVentureRoundInvestmentsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedRoundInvestmentsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureDutchDynamicRoundsCursorResponseTransformer = (data: any) => Promise<GetVentureDutchDynamicRoundsCursorResponse>;

export const GetVentureDutchDynamicRoundsCursorResponseTransformer: GetVentureDutchDynamicRoundsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureDutchDynamicRoundsOffsetResponseTransformer = (data: any) => Promise<GetVentureDutchDynamicRoundsOffsetResponse>;

export const GetVentureDutchDynamicRoundsOffsetResponseTransformer: GetVentureDutchDynamicRoundsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedDutchDynamicRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureRegularDynamicRoundsCursorResponseTransformer = (data: any) => Promise<GetVentureRegularDynamicRoundsCursorResponse>;

export const GetVentureRegularDynamicRoundsCursorResponseTransformer: GetVentureRegularDynamicRoundsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureRegularDynamicRoundsOffsetResponseTransformer = (data: any) => Promise<GetVentureRegularDynamicRoundsOffsetResponse>;

export const GetVentureRegularDynamicRoundsOffsetResponseTransformer: GetVentureRegularDynamicRoundsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedRegularDynamicRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureFixedTotalRoundsCursorResponseTransformer = (data: any) => Promise<GetVentureFixedTotalRoundsCursorResponse>;

export const GetVentureFixedTotalRoundsCursorResponseTransformer: GetVentureFixedTotalRoundsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVentureFixedTotalRoundsOffsetResponseTransformer = (data: any) => Promise<GetVentureFixedTotalRoundsOffsetResponse>;

export const GetVentureFixedTotalRoundsOffsetResponseTransformer: GetVentureFixedTotalRoundsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedFixedTotalRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVenturePartialTotalRoundsCursorResponseTransformer = (data: any) => Promise<GetVenturePartialTotalRoundsCursorResponse>;

export const GetVenturePartialTotalRoundsCursorResponseTransformer: GetVenturePartialTotalRoundsCursorResponseTransformer = async (data) => {
    GetCursorPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer(data);
    return data;
};

export type GetVenturePartialTotalRoundsOffsetResponseTransformer = (data: any) => Promise<GetVenturePartialTotalRoundsOffsetResponse>;

export const GetVenturePartialTotalRoundsOffsetResponseTransformer: GetVenturePartialTotalRoundsOffsetResponseTransformer = async (data) => {
    GetOffsetPaginatedPartialTotalRoundsOutputBodyModelResponseTransformer(data);
    return data;
};