CREATE TYPE bank_account_types AS ENUM(
    'investment',
    'credit',
    'depository',
    'loan',
    'brokerage',
    'other'
);

CREATE TYPE bank_account_sub_types AS ENUM(
    '401a',
    '401k',
    '403B',
    '457b',
    '529',
    'auto',
    'brokerage',
    'business',
    'cash isa',
    'cash management',
    'cd',
    'checking',
    'commercial',
    'construction',
    'consumer',
    'credit card',
    'crypto exchange',
    'ebt',
    'education savings account',
    'fixed annuity',
    'gic',
    'health reimbursement arrangement',
    'home equity',
    'hsa',
    'isa',
    'ira',
    'keogh',
    'lif',
    'life insurance',
    'line of credit',
    'lira',
    'loan',
    'lrif',
    'lrsp',
    'money market',
    'mortgage',
    'mutual fund',
    'non-custodial wallet',
    'non-taxable brokerage account',
    'other',
    'other insurance',
    'other annuity',
    'overdraft',
    'paypal',
    'payroll',
    'pension',
    'prepaid',
    'prif',
    'profit sharing plan',
    'rdsp',
    'resp',
    'retirement',
    'rlif',
    'roth',
    'roth 401k',
    'rrif',
    'rrsp',
    'sarsep',
    'savings',
    'sep ira',
    'simple ira',
    'sipp',
    'stock plan',
    'student',
    'thrift savings plan',
    'tfsa',
    'trust',
    'ugma',
    'utma',
    'variable annuity'
);

CREATE TYPE bank_account_verification_statuses AS ENUM(
    'automatically_verified',
    'pending_automatic_verification',
    'pending_manual_verification',
    'manually_verified',
    'verification_expired',
    'verification_failed',
    'database_matched',
    'database_insights_pass',
    'database_insights_pass_with_caution',
    'database_insights_fail'
);

CREATE TYPE bank_account_holder_categories AS ENUM('business', 'personal', 'unrecognized');

CREATE TABLE
    plaid_bank_accounts (
        id SERIAL PRIMARY KEY NOT NULL,
        linked_account_id INT REFERENCES linked_accounts (id) NOT NULL,
        remote_id TEXT NOT NULL,
        available_balance DECIMAL,
        current_balance DECIMAL,
        limit_amount DECIMAL,
        iso_currency_code TEXT,
        unofficial_currency_code TEXT,
        balance_last_updated_at TIMESTAMP WITH TIME ZONE,
        mask TEXT,
        NAME TEXT NOT NULL,
        official_name TEXT,
        TYPE bank_account_types NOT NULL,
        verification_status bank_account_verification_statuses NOT NULL,
        subtype bank_account_sub_types,
        verification_name TEXT NOT NULL,
        holder_category bank_account_holder_categories,
        persistant_account_id TEXT NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE
    );