/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    'blog-categories': BlogCategory;
    media: Media;
    users: User;
    pages: Page;
    posts: Post;
    redirects: Redirect;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': Settings;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  slug?: string | null;
  slugLock?: boolean | null;
  title: string;
  showInFilter?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: 'admin'[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug?: string | null;
  slugLock?: boolean | null;
  title: string;
  hero: {
    type: 'none' | 'standard' | 'slider' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'parallax';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    title?: string | null;
    subtitle?: string | null;
    size?: ('large' | 'medium' | 'small') | null;
    background?: (number | null) | Media;
    media?: (number | null) | Media;
    slides?:
      | {
          pretitle?: string | null;
          title?: string | null;
          description?: string | null;
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?: {
                    relationTo: 'pages';
                    value: number | Page;
                  } | null;
                  url?: string | null;
                  label: string;
                  appearance?: ('default' | 'outline') | null;
                };
                id?: string | null;
              }[]
            | null;
          background?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    autoplay?: boolean | null;
    delay?: number | null;
    fade?: boolean | null;
  };
  layout?:
    | (
        | ArchiveBlock
        | BannerBlock
        | CallToActionBlock
        | CodeBlock
        | ContentBlock
        | MediaBlock
        | ContactBlock
        | TypographyBlock
        | LatestPostsBlock
        | CardBlock
        | {
            gridStyle: 'basic' | 'masonry' | 'responsive';
            columns?: number | null;
            gap?: number | null;
            content?:
              | {
                  contentType?: ('blocks' | 'richText') | null;
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  blocks?:
                    | (
                        | ArchiveBlock
                        | BannerBlock
                        | CallToActionBlock
                        | CodeBlock
                        | MediaBlock
                        | TypographyBlock
                        | CardBlock
                      )[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | BlogCategory)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | BlogCategory)[] | null;
  meta?: {
    title?: string | null;
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  gapX?: number | null;
  gapY?: number | null;
  columns?:
    | {
        type?: ('blocks' | 'richText') | null;
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        height?: number | null;
        align?: ('start' | 'center' | 'end') | null;
        enableLink?: boolean | null;
        enableBackgroundImage?: boolean | null;
        backgroundImage?: (number | null) | Media;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        blocks?:
          | (
              | ArchiveBlock
              | BannerBlock
              | CallToActionBlock
              | CodeBlock
              | MediaBlock
              | TypographyBlock
              | CardBlock
              | {
                  gridStyle: 'basic' | 'masonry' | 'responsive';
                  columns?: number | null;
                  gap?: number | null;
                  content?:
                    | {
                        contentType?: ('blocks' | 'richText') | null;
                        richText?: {
                          root: {
                            type: string;
                            children: {
                              type: string;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        } | null;
                        blocks?:
                          | (
                              | ArchiveBlock
                              | BannerBlock
                              | CallToActionBlock
                              | CodeBlock
                              | MediaBlock
                              | TypographyBlock
                              | CardBlock
                            )[]
                          | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'grid';
                }
            )[]
          | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  position?: ('default' | 'fullscreen') | null;
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TypographyBlock".
 */
export interface TypographyBlock {
  type?: ('sub-title-body' | 'title-body' | 'title' | 'subtitle' | 'body') | null;
  enableLinks?: boolean | null;
  align?: ('left' | 'center' | 'right') | null;
  title?: string | null;
  subTitle?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('default' | 'secondary' | 'none') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'typography';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlock".
 */
export interface CardBlock {
  type?: ('icon' | 'product' | 'service') | null;
  icon?:
    | (
        | 'moon'
        | 'heart-eyes'
        | 'swimming'
        | 'walking'
        | 'wave'
        | 'theater-masks'
        | 'heart'
        | 'sleeping'
        | 'stress'
        | 'aches'
        | 'sick'
      )
    | null;
  title?: string | null;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  title: string;
  message: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostsBlock".
 */
export interface LatestPostsBlock {
  title: string;
  subtitle?: string | null;
  body?: string | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
    label: string;
    appearance?: ('default' | 'outline') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'latest-posts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  slug?: T;
  slugLock?: T;
  title?: T;
  showInFilter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  slugLock?: T;
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        title?: T;
        subtitle?: T;
        size?: T;
        background?: T;
        media?: T;
        slides?:
          | T
          | {
              pretitle?: T;
              title?: T;
              description?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              background?: T;
              id?: T;
            };
        autoplay?: T;
        delay?: T;
        fade?: T;
      };
  layout?:
    | T
    | {
        archive?:
          | T
          | {
              introContent?: T;
              populateBy?: T;
              relationTo?: T;
              categories?: T;
              limit?: T;
              selectedDocs?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              style?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              richText?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        code?:
          | T
          | {
              language?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              gapX?: T;
              gapY?: T;
              columns?:
                | T
                | {
                    type?: T;
                    size?: T;
                    height?: T;
                    align?: T;
                    enableLink?: T;
                    enableBackgroundImage?: T;
                    backgroundImage?: T;
                    richText?: T;
                    blocks?:
                      | T
                      | {
                          archive?:
                            | T
                            | {
                                introContent?: T;
                                populateBy?: T;
                                relationTo?: T;
                                categories?: T;
                                limit?: T;
                                selectedDocs?: T;
                                id?: T;
                                blockName?: T;
                              };
                          banner?:
                            | T
                            | {
                                style?: T;
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          cta?:
                            | T
                            | {
                                richText?: T;
                                links?:
                                  | T
                                  | {
                                      link?:
                                        | T
                                        | {
                                            type?: T;
                                            newTab?: T;
                                            reference?: T;
                                            url?: T;
                                            label?: T;
                                            appearance?: T;
                                          };
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          code?:
                            | T
                            | {
                                language?: T;
                                code?: T;
                                id?: T;
                                blockName?: T;
                              };
                          mediaBlock?:
                            | T
                            | {
                                position?: T;
                                media?: T;
                                id?: T;
                                blockName?: T;
                              };
                          typography?:
                            | T
                            | {
                                type?: T;
                                enableLinks?: T;
                                align?: T;
                                title?: T;
                                subTitle?: T;
                                body?: T;
                                links?:
                                  | T
                                  | {
                                      link?:
                                        | T
                                        | {
                                            type?: T;
                                            newTab?: T;
                                            reference?: T;
                                            url?: T;
                                            label?: T;
                                            appearance?: T;
                                          };
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          card?:
                            | T
                            | {
                                type?: T;
                                icon?: T;
                                title?: T;
                                description?: T;
                                id?: T;
                                blockName?: T;
                              };
                          grid?:
                            | T
                            | {
                                gridStyle?: T;
                                columns?: T;
                                gap?: T;
                                content?:
                                  | T
                                  | {
                                      contentType?: T;
                                      richText?: T;
                                      blocks?:
                                        | T
                                        | {
                                            archive?:
                                              | T
                                              | {
                                                  introContent?: T;
                                                  populateBy?: T;
                                                  relationTo?: T;
                                                  categories?: T;
                                                  limit?: T;
                                                  selectedDocs?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            banner?:
                                              | T
                                              | {
                                                  style?: T;
                                                  content?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            cta?:
                                              | T
                                              | {
                                                  richText?: T;
                                                  links?:
                                                    | T
                                                    | {
                                                        link?:
                                                          | T
                                                          | {
                                                              type?: T;
                                                              newTab?: T;
                                                              reference?: T;
                                                              url?: T;
                                                              label?: T;
                                                              appearance?: T;
                                                            };
                                                        id?: T;
                                                      };
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            code?:
                                              | T
                                              | {
                                                  language?: T;
                                                  code?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            mediaBlock?:
                                              | T
                                              | {
                                                  position?: T;
                                                  media?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            typography?:
                                              | T
                                              | {
                                                  type?: T;
                                                  enableLinks?: T;
                                                  align?: T;
                                                  title?: T;
                                                  subTitle?: T;
                                                  body?: T;
                                                  links?:
                                                    | T
                                                    | {
                                                        link?:
                                                          | T
                                                          | {
                                                              type?: T;
                                                              newTab?: T;
                                                              reference?: T;
                                                              url?: T;
                                                              label?: T;
                                                              appearance?: T;
                                                            };
                                                        id?: T;
                                                      };
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            card?:
                                              | T
                                              | {
                                                  type?: T;
                                                  icon?: T;
                                                  title?: T;
                                                  description?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                          };
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                        };
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              position?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              message?: T;
              id?: T;
              blockName?: T;
            };
        typography?:
          | T
          | {
              type?: T;
              enableLinks?: T;
              align?: T;
              title?: T;
              subTitle?: T;
              body?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'latest-posts'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              body?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
              blockName?: T;
            };
        card?:
          | T
          | {
              type?: T;
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              gridStyle?: T;
              columns?: T;
              gap?: T;
              content?:
                | T
                | {
                    contentType?: T;
                    richText?: T;
                    blocks?:
                      | T
                      | {
                          archive?:
                            | T
                            | {
                                introContent?: T;
                                populateBy?: T;
                                relationTo?: T;
                                categories?: T;
                                limit?: T;
                                selectedDocs?: T;
                                id?: T;
                                blockName?: T;
                              };
                          banner?:
                            | T
                            | {
                                style?: T;
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          cta?:
                            | T
                            | {
                                richText?: T;
                                links?:
                                  | T
                                  | {
                                      link?:
                                        | T
                                        | {
                                            type?: T;
                                            newTab?: T;
                                            reference?: T;
                                            url?: T;
                                            label?: T;
                                            appearance?: T;
                                          };
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          code?:
                            | T
                            | {
                                language?: T;
                                code?: T;
                                id?: T;
                                blockName?: T;
                              };
                          mediaBlock?:
                            | T
                            | {
                                position?: T;
                                media?: T;
                                id?: T;
                                blockName?: T;
                              };
                          typography?:
                            | T
                            | {
                                type?: T;
                                enableLinks?: T;
                                align?: T;
                                title?: T;
                                subTitle?: T;
                                body?: T;
                                links?:
                                  | T
                                  | {
                                      link?:
                                        | T
                                        | {
                                            type?: T;
                                            newTab?: T;
                                            reference?: T;
                                            url?: T;
                                            label?: T;
                                            appearance?: T;
                                          };
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          card?:
                            | T
                            | {
                                type?: T;
                                icon?: T;
                                title?: T;
                                description?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        overview?: T;
        title?: T;
        image?: T;
        description?: T;
        preview?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        overview?: T;
        title?: T;
        image?: T;
        description?: T;
        preview?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface Settings {
  id: number;
  general?: {
    appName?: string | null;
    appDescription?: string | null;
  };
  admin?: {
    email?: string | null;
    phone_number?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  siteHeader?: {
    logo?: (number | null) | Media;
  };
  shopHeader?: {
    navItems?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  siteFooter?: {
    navItems?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  shopFooter?: {
    navItems?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        appName?: T;
        appDescription?: T;
      };
  admin?:
    | T
    | {
        email?: T;
        phone_number?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  siteHeader?:
    | T
    | {
        logo?: T;
      };
  shopHeader?:
    | T
    | {
        navItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  siteFooter?:
    | T
    | {
        navItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  shopFooter?:
    | T
    | {
        navItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}