name: Production Deployment - API
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
      - packages/**
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy API to Fly.io
    runs-on: ubuntu-latest
    concurrency: fly-production
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run linter
        run: bun run lint
        working-directory: ./apps/api
      - name: Check TypeScript
        run: NODE_OPTIONS="--max-old-space-size=8192" bun run typecheck
        working-directory: ./apps/api
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --dockerfile apps/api/Dockerfile --config apps/api/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}